stages:
  - deploy

deploy:
  stage: deploy
  only:
    - main
  tags:
    - shared
  script:
    - docker compose -p js-project down
    - docker compose -p js-project up --build --remove-orphans --detach
