export const environment = {
  production: true,
  // TODO: Update when back-end is deployed at domain
  apiUrl: 'http://localhost:8080/api/v1/',
  API_REGISTER_ENDPOINT: 'Identity/Account/Register',
  API_LOGIN_ENDPOINT: 'Identity/Account/Login',
  API_LOGOUT_ENDPOINT: 'Identity/Account/Logout',
  API_REFRESH_ENDPOINT: 'Identity/Account/RefreshToken',
  API_AUTHOR_ENDPOINT: 'Author',
  API_AUTHOR_ROLE_ENDPOINT: 'AuthorRole',
  API_GENRE_ENDPOINT: 'Genre',
  API_PROJECT_ENDPOINT: 'Project',
  API_PROJECT_AUTHOR_ENDPOINT: 'ProjectAuthor',
  API_PROJECT_AUTHOR_ROLE_ENDPOINT: 'ProjectAuthorRole',
  API_PROJECT_DETAILS_ENDPOINT: 'ProjectDetails',
  API_PROJECT_DETAILS_GENRE_ENDPOINT: 'ProjectDetailsGenre',
  API_PROJECT_DETAILS_TAG_ENDPOINT: 'ProjectDetailsTag',
  API_PROJECT_TYPE_ENDPOINT: 'ProjectType',
  API_TAG_ENDPOINT: 'Tag',
};
